:badges:
:icons:
:toc-title: Agenda
:toc2: left
:iconsdir: http://people.redhat.com/~jduncan/images/icons
:imagesdir: ../_images
:date: 09-Aug-2016
:location: New York, NY
:tower_url: https://ansible-tower.c2spaas.com
:toclevels: 3
:source-highlighter: highlight.js

= Containers Workshop

.Before We Get Started
****
[.lead]
Overview

Today is meant for anyone who has any exposure to Containers, whether you have used it or not. We are going to start with a short overview (yes, slideware) and then we'll get into the lab as soon as possible. That is where we will spend most of our time.

[.lead]
Your Responsibilities

* Have a discussion. This will be boring if it's just us up here talking for over 2 hours.
* Participate. Have questions. Have opinions.

Hopefully you have your laptop with you. If not, please find a shoulder-surfing buddy.

[IMPORTANT]
.WiFi Access
====
ssid: `Red Hat Guest`

password: `atomic2016`
====
****


.Today's Team
****
[.lead]
Jonathan Van Meter - Solutions Architect

[.lead]
Alex Jacocks - Solutions Architect

[.lead]
Brad Sollar - Solutions Architect



****
== Document Copyright

This document was created by and for Red Hat, Inc. It is being released under link:https://creativecommons.org/licenses/by/4.0/[Creative Commons License 4.0]. You are free to re-use it in whole or in part.

You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.


=== Infrastructure

For this lab, we will be using a RHEL 7 AMI,  We are running it in an link:https://aws.amazon.com/marketplace/pp/B019NS7T5I[`Red Hat Enterprise Linux (RHEL) 7.2 (HVM)`] AWS instance.
